### ISSUE TITLE
Add support for PoE pins for Pi 4 / Rock Pi. 

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/IP67-Enclosure#5]
With the new design for the Raspberry Pi 3B+/4/Rock Pi 4, there are four new pins dedicated to the PoE HAT as can be seen here:
![IMG_0235](https://user-images.githubusercontent.com/357664/138416662-b6ce0272-c2ad-4f9a-a79c-d801a5e96a93.jpeg)

I was able to get things to work just fine using this board by manually wiring things up:

![IMG_0234](https://user-images.githubusercontent.com/357664/138416601-23adf043-4812-4e85-981c-ccd5c26ccb6e.jpeg)

In order to add support for this, we need to add new pins to the board for this as you can't fit the board otherwise.

**Comment by shawaj** [comment]
Closing as we can stack directly on the RockPi as per below photo:

![signal-2021-10-22-18-24-18-093](https://user-images.githubusercontent.com/3359418/138591413-07b8b502-72b1-4cbb-8ff7-ed1c8f5c31ed.jpg)
